const fs = require('node:fs');
const path = require('node:path');
const output = path.join(__dirname, '..', 'dist');
fs.mkdirSync(output, { recursive: true });
if (!fs.existsSync(path.join(output, 'index.html'))) throw new Error('Run Vite build before exporting legacy assets.');
const files = ['membros.html', 'membros-en.html', 'membro.html', 'membro-en.html', 'style.css', 'identity.css', 'i18n.js', 'assets', 'components', 'zohoverify'];
for (const file of files) fs.cpSync(path.join(__dirname, '..', file), path.join(output, file), { recursive: true });
const html = fs.readFileSync(path.join(output, 'index.html'), 'utf8');
fs.writeFileSync(path.join(output, 'index-en.html'), html.replace('lang="pt-BR"', 'lang="en"').replace('Liga de robótica do Inteli', 'Inteli Robotics League'));
console.log('React league and connected legacy member pages exported to dist');
